config/routes.rb
Rails.application.routes.draw do
  resources :photos, only: [:new, :create, :index]
  root to: 'photos#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	dragonfly_accessor :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
    @photos = Photo.all
  end
 
  def new
    @photo = Photo.new
  end
 
  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = "Photo saved!"
      redirect_to photos_path
    else
      render 'new'
    end
  end
 
  private
 
  def photo_params
    params.require(:photo).permit(:image, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DragonFlyUploading</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<h1>List of photos</h1>
 
<%= link_to 'Add your photo', new_photo_path, class: 'btn btn-lg btn-primary' %>
 
<ul class="row" id="photos-list">
  <% @photos.each do |photo| %>
    <li class="col-xs-3">
      <%= link_to image_tag(photo.image.thumb('180x180#').url, alt: photo.title, class: 'img-thumbnail'),
                  photo.image.url, target: '_blank' %>
      <p><%= photo.title %></p>
    </li>
  <% end %>
</ul>

app/views/photos/new.html.erb
<h1>New photo</h1>
 
<%= form_for @photo do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>
 
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, required: true %>
  </div>
 
  <%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>
<% end %>